Update dependencies
rylev/wepl pull request #8
Opened 2024-02-13 11:41 UTC by jaseb

Update the README.md to mention Wasmtime 17.0, update to newer dependencies in Cargo.toml, and update Cargo.lock.

Amend `runtime.rs` to use `wasmtime::component::ResourceTable` as per changes in Wasmtime. See [`wasmtime_wasi::preview2::Table`](https://github.com/bytecodealliance/wasmtime/pull/7655)

2024-02-13 13:07 UTC, rylev requested changes
Thanks so much for this! Overall looks good. I just have one comment about some lingering comments that we probably want to remove.

2024-02-13 23:32 UTC, jaseb commented on Cargo.toml
> +# wasi-virt = { git = "https://github.com/bytecodealliance/WASI-Virt", rev = "6801514735cb78b385221e225c554bc043038c2f" }
No worries, fixed.

2024-02-13 23:54 UTC, rylev commented
Seems that you'll need to run `cargo fmt` for CI to pass.

2024-02-14 00:05 UTC, jaseb commented
> Seems that you'll need to run `cargo fmt` for CI to pass.

Just noticed that, sorted.

2024-02-14 13:55 UTC, merged